#!/bin/sh /etc/rc.common
# Copyright (C) 2016 OpenWrt.org
# 基于 OpenWrt packages 的 qemu-ga.init，保留官方 procd 生命周期。
# 25.12 原脚本没有通道检测；实体机或未启用 Agent 的虚拟机应静默跳过。

START=99
USE_PROCD=1

BIN=/usr/bin/qemu-ga
PORT=/dev/virtio-ports/org.qemu.guest_agent.0

start_service() {
	[ -c "$PORT" ] || return 0

	procd_open_instance
	procd_set_param command "$BIN"
	procd_set_param respawn
	procd_set_param stderr 1
	procd_close_instance
}
